//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PahramcyOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int Id_admin { get; set; }
        public string Email_Admin { get; set; }
        public string Password_Admin { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
    }
}
