//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PahramcyOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int id_user { get; set; }
        public System.TimeSpan added_at { get; set; }
        public double sum { get; set; }
    
        public virtual User User { get; set; }
    }
}
