//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PahramcyOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.Carts = new HashSet<Cart>();
        }
    
        public int Id { get; set; }
        public string pro_TradName { get; set; }
        public double pro_prices { get; set; }
        public int pro_quantity { get; set; }
        public string pro_company { get; set; }
        public string pro_pharmacology { get; set; }
        public string pro_type { get; set; }
        public string pro_GenericName { get; set; }
        public string pro_image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
    }
}
